version: '3'
services:
  mysql-db:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newsdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql